# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jiujiu' do
pod 'AFNetworking'
pod 'MJRefresh', '~> 3.0.7'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.2'
pod 'MBProgressHUD'
pod 'FMDB'
pod 'pop'
pod 'KSCrash'
pod 'Reachability'
pod 'YYImage'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'CocoaAsyncSocket' 
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Jiujiu

  target 'JiujiuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JiujiuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
